### ISSUE TITLE
complete log is one message

### ISSUE THREAD

**Issue by schochastics** [gesiscss/WhatsR#23]
This is the summary of a chat with two people from June 2022 onwards.
```r
tst <- parse_chat("raw_chat.txt",os="android",verbose = TRUE)
sum <- summarize_chat(tst)
#>$NumberOfMessages
#>[1] 1
#>...
#>$NumberOfParticipants
#>[1] 1
#>
#>$StartDate
#>[1] "2022-06-08 15:23:00 UTC"
#>
#>$EndDate
#>[1] "2022-06-08 15:23:00 UTC"
#> ...
```

Seems like the whole history is interpreted as one message. (Could be that this causes #21 to be so slow for me, because only one extremely long string is checked)

**Comment by schochastics** [comment]
Did not investigate much yet, but the first time I notice a problem is here

https://github.com/gesiscss/WhatsR/blob/e7ea86caab03a4337f02a8a7a1297868e6e7d1fa/R/parse_android.R#L81-L85

because further down

https://github.com/gesiscss/WhatsR/blob/e7ea86caab03a4337f02a8a7a1297868e6e7d1fa/R/parse_android.R#L93-L96

returns only one date

**Comment by schochastics** [comment]
Ok this is definitely related to #20 because this code doesnt split the chat for me. So the issues from the comment before are because of the failure here.

https://github.com/gesiscss/WhatsR/blob/e7ea86caab03a4337f02a8a7a1297868e6e7d1fa/R/parse_android.R#L54

Fixing #20 should resolve this issue here and also potentially #21

**Comment by JuKo007** [comment]
Fixed through merge
